name: ChargePoint Waitlist Automation

on:
  schedule:
    - cron: '45 6 * * *'  # 8:59 AM PST
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    env:
      CHARGEPOINT_EMAIL: ${{ secrets.CHARGEPOINT_EMAIL }}
      CHARGEPOINT_PASSWORD: ${{ secrets.CHARGEPOINT_PASSWORD }}
      CHARGEPOINT_STATION_NAME: ${{ secrets.CHARGEPOINT_STATION_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run waitlist script
        run: python waitlist_script.py
